all: libutils.so main.exe prog.exe

libutils.so: utils.c
	gcc -std=c99 -shared -fPIC -I. -O2 -o libutils.so utils.c -luuid

main.exe: main.c
	gcc -std=c99 -I. -L. -O2 -o main.exe main.c -lutils 

prog.exe: iso_vst.o prog.f90
	gfortran -cpp -L. -o prog.exe iso_vst.o prog.f90 -lutils

iso_vst.o: iso_vst.f90
	gfortran -c -O2 -o iso_vst.o iso_vst.f90

docs:
	doxygen Doxyfile.linux

clean:
	rm -f *.exe *.o *.so *.mod

